- hosts: webservers
  vars:
    mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
    mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
    mssql_accept_microsoft_sql_server_standard_eula: true
    mssql_version: 2022
    mssql_password: "p@55w0rD"
    mssql_edition: Evaluation
    mssql_tcp_port: 1433
    mssql_datadir: /home/cloud-user/__datadirs/mssql
    mssql_post_input_sql_file:
      - "../files/script1.sql"
    # roles:
    #   - microsoft.sql.server
  collections: 
    - microsoft.sql
  tasks:
    import_role: microsoft.sql.server